### PR TITLE
Set exec bit for build script

### LINKED ISSUE #43: build firmware get error
```
D:\IoT\NodeMCU V2\nodemcu-firmware>docker image ls
REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
marcelstoer/nodemcu-build          latest              b9049eff6bf7        2 days ago          342MB
marcelstoer/nodemcu-build          ok                  f24c34189836        7 days ago          342MB
```

```
D:\IoT\NodeMCU V2\nodemcu-firmware>docker run --rm -ti -v "D:\IoT\NodeMCU V2\nodemcu-firmware":/opt/nodemcu-firmware marcelstoer/nodemcu-build build
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"build\": executable file not found in $PATH": unknown.
```

### PR DESCRIPTION
**Pull request by mcspr**
Fixes #43

### CODE REVIEW

**Review by HHHartmann — CHANGES_REQUESTED** [review]
This seems to strike only when the image is built on a Linux System. On Windows the x bit is being set.
Could you please also correct this for the other script lfs-image?

**Review by HHHartmann — CHANGES_REQUESTED** [review]
Removed duplicate post.

**Comment by mcspr** [comment]
Ooops, did not notice lfs-image. Rebased with both scripts +x'ed

**Comment by marcelstoer** [comment]
Thank you both!

**Pull request merged**
