### PR TITLE
Support custom targets for build command

### PR DESCRIPTION
**Pull request by mk-pmb**
Also thanks for this project! :moneybag:

### CODE REVIEW

**Comment by HHHartmann** [comment]
Maybe we could just pass everything else on the command line after`build` just like in `lfs-image`

**Comment by HHHartmann** [comment]
It might also make sense to also omit `clean` if custom targets are given.

**Comment by mk-pmb** [comment]
> Maybe we could just pass everything else on the command line after`build` just like in `lfs-image`

I prefer the env var because it gives those values a name. Makes it easier to understand their role.

> It might also make sense to also omit `clean` if custom targets are given.

You're right, thanks! Fixed.

**Comment by HHHartmann** [comment]
> I prefer the env var because it gives those values a name. Makes it easier to understand their role.

True. But just adding the targets after make/build is how it is done on cli and would feel the natural and obvious way to do it.

**Comment by mk-pmb** [comment]
Actually, why not have both? Once this is merged, you could just make another PR that puts a line like

```bash
if [ -n "$*" ]; then BUILD_MAKE_TARGETS=; fi
```

above the make commands, and add `"$@"` to the end of the make command.

Edit: Nope, that would add to the defaults. I'll rewrite my PR so it sets those defaults earlier, so you can overwrite them easier.

**Comment by HHHartmann** [comment]
Yeah we can have both. Great. Heading for bed again now.

**Comment by HHHartmann** [comment]
So this one is ready to go?

**Comment by marcelstoer** [comment]
Sorry, somehow must have lost track of this.

**Pull request merged**
